//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace Portal.Modules.Forum.Data {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class ThreadData : DataSet {
        
        private ThreadDataTable tableThread;
        
        private DataRelation relationThreadThread;
        
        public ThreadData() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected ThreadData(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["Thread"] != null)) {
                    this.Tables.Add(new ThreadDataTable(ds.Tables["Thread"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public ThreadDataTable Thread {
            get {
                return this.tableThread;
            }
        }
        
        public override DataSet Clone() {
            ThreadData cln = ((ThreadData)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["Thread"] != null)) {
                this.Tables.Add(new ThreadDataTable(ds.Tables["Thread"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        public void InitVars() {
            this.tableThread = ((ThreadDataTable)(this.Tables["Thread"]));
            if ((this.tableThread != null)) {
                this.tableThread.InitVars();
            }
            this.relationThreadThread = this.Relations["ThreadThread"];
        }
        
        private void InitClass() {
            this.DataSetName = "ThreadData";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/ThreadData.xsd";
            this.Locale = new System.Globalization.CultureInfo("en-US");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tableThread = new ThreadDataTable();
            this.Tables.Add(this.tableThread);
            ForeignKeyConstraint fkc;
            fkc = new ForeignKeyConstraint("ThreadThread", new DataColumn[] {
                        this.tableThread.IdColumn}, new DataColumn[] {
                        this.tableThread.ParentColumn});
            this.tableThread.Constraints.Add(fkc);
            fkc.AcceptRejectRule = System.Data.AcceptRejectRule.None;
            fkc.DeleteRule = System.Data.Rule.Cascade;
            fkc.UpdateRule = System.Data.Rule.Cascade;
            this.relationThreadThread = new DataRelation("ThreadThread", new DataColumn[] {
                        this.tableThread.IdColumn}, new DataColumn[] {
                        this.tableThread.ParentColumn}, false);
            this.Relations.Add(this.relationThreadThread);
        }
        
        private bool ShouldSerializeThread() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void ThreadRowChangeEventHandler(object sender, ThreadRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class ThreadDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnTitle;
            
            private DataColumn columnText;
            
            private DataColumn columnAuthor;
            
            private DataColumn columnEmail;
            
            private DataColumn columnUserId;
            
            private DataColumn columnId;
            
            private DataColumn columnParent;
            
            private DataColumn columnDateTime;
            
            public ThreadDataTable() : 
                    base("Thread") {
                this.InitClass();
            }
            
            public ThreadDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            public DataColumn TitleColumn {
                get {
                    return this.columnTitle;
                }
            }
            
            public DataColumn TextColumn {
                get {
                    return this.columnText;
                }
            }
            
            public DataColumn AuthorColumn {
                get {
                    return this.columnAuthor;
                }
            }
            
            public DataColumn EmailColumn {
                get {
                    return this.columnEmail;
                }
            }
            
            public DataColumn UserIdColumn {
                get {
                    return this.columnUserId;
                }
            }
            
            public DataColumn IdColumn {
                get {
                    return this.columnId;
                }
            }
            
            public DataColumn ParentColumn {
                get {
                    return this.columnParent;
                }
            }
            
            public DataColumn DateTimeColumn {
                get {
                    return this.columnDateTime;
                }
            }
            
            public ThreadRow this[int index] {
                get {
                    return ((ThreadRow)(this.Rows[index]));
                }
            }
            
            public event ThreadRowChangeEventHandler ThreadRowChanged;
            
            public event ThreadRowChangeEventHandler ThreadRowChanging;
            
            public event ThreadRowChangeEventHandler ThreadRowDeleted;
            
            public event ThreadRowChangeEventHandler ThreadRowDeleting;
            
            public void AddThreadRow(ThreadRow row) {
                this.Rows.Add(row);
            }
            
            public ThreadRow AddThreadRow(string Title, string Text, string Author, string Email, string UserId, ThreadRow parentThreadRowByThreadThread, System.DateTime DateTime) {
                ThreadRow rowThreadRow = ((ThreadRow)(this.NewRow()));
                rowThreadRow.ItemArray = new object[] {
                        Title,
                        Text,
                        Author,
                        Email,
                        UserId,
                        null,
                        parentThreadRowByThreadThread[5],
                        DateTime};
                this.Rows.Add(rowThreadRow);
                return rowThreadRow;
            }
            
            public ThreadRow FindById(int Id) {
                return ((ThreadRow)(this.Rows.Find(new object[] {
                            Id})));
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                ThreadDataTable cln = ((ThreadDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new ThreadDataTable();
            }
            
            public void InitVars() {
                this.columnTitle = this.Columns["Title"];
                this.columnText = this.Columns["Text"];
                this.columnAuthor = this.Columns["Author"];
                this.columnEmail = this.Columns["Email"];
                this.columnUserId = this.Columns["UserId"];
                this.columnId = this.Columns["Id"];
                this.columnParent = this.Columns["Parent"];
                this.columnDateTime = this.Columns["DateTime"];
            }
            
            private void InitClass() {
                this.columnTitle = new DataColumn("Title", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnTitle);
                this.columnText = new DataColumn("Text", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnText);
                this.columnAuthor = new DataColumn("Author", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnAuthor);
                this.columnEmail = new DataColumn("Email", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnEmail);
                this.columnUserId = new DataColumn("UserId", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnUserId);
                this.columnId = new DataColumn("Id", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnId);
                this.columnParent = new DataColumn("Parent", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnParent);
                this.columnDateTime = new DataColumn("DateTime", typeof(System.DateTime), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnDateTime);
                this.Constraints.Add(new UniqueConstraint("ThreadDataKey1", new DataColumn[] {
                                this.columnId}, true));
                this.columnId.AutoIncrement = true;
                this.columnId.AllowDBNull = false;
                this.columnId.Unique = true;
            }
            
            public ThreadRow NewThreadRow() {
                return ((ThreadRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new ThreadRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(ThreadRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.ThreadRowChanged != null)) {
                    this.ThreadRowChanged(this, new ThreadRowChangeEvent(((ThreadRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.ThreadRowChanging != null)) {
                    this.ThreadRowChanging(this, new ThreadRowChangeEvent(((ThreadRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.ThreadRowDeleted != null)) {
                    this.ThreadRowDeleted(this, new ThreadRowChangeEvent(((ThreadRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.ThreadRowDeleting != null)) {
                    this.ThreadRowDeleting(this, new ThreadRowChangeEvent(((ThreadRow)(e.Row)), e.Action));
                }
            }
            
            public void RemoveThreadRow(ThreadRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class ThreadRow : DataRow {
            
            private ThreadDataTable tableThread;
            
            public ThreadRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tableThread = ((ThreadDataTable)(this.Table));
            }
            
            public string Title {
                get {
                    try {
                        return ((string)(this[this.tableThread.TitleColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Der Wert kann nicht ermittelt werden, da er DBNull ist.", e);
                    }
                }
                set {
                    this[this.tableThread.TitleColumn] = value;
                }
            }
            
            public string Text {
                get {
                    try {
                        return ((string)(this[this.tableThread.TextColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Der Wert kann nicht ermittelt werden, da er DBNull ist.", e);
                    }
                }
                set {
                    this[this.tableThread.TextColumn] = value;
                }
            }
            
            public string Author {
                get {
                    try {
                        return ((string)(this[this.tableThread.AuthorColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Der Wert kann nicht ermittelt werden, da er DBNull ist.", e);
                    }
                }
                set {
                    this[this.tableThread.AuthorColumn] = value;
                }
            }
            
            public string Email {
                get {
                    try {
                        return ((string)(this[this.tableThread.EmailColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Der Wert kann nicht ermittelt werden, da er DBNull ist.", e);
                    }
                }
                set {
                    this[this.tableThread.EmailColumn] = value;
                }
            }
            
            public string UserId {
                get {
                    try {
                        return ((string)(this[this.tableThread.UserIdColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Der Wert kann nicht ermittelt werden, da er DBNull ist.", e);
                    }
                }
                set {
                    this[this.tableThread.UserIdColumn] = value;
                }
            }
            
            public int Id {
                get {
                    return ((int)(this[this.tableThread.IdColumn]));
                }
                set {
                    this[this.tableThread.IdColumn] = value;
                }
            }
            
            public int Parent {
                get {
                    try {
                        return ((int)(this[this.tableThread.ParentColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Der Wert kann nicht ermittelt werden, da er DBNull ist.", e);
                    }
                }
                set {
                    this[this.tableThread.ParentColumn] = value;
                }
            }
            
            public System.DateTime DateTime {
                get {
                    try {
                        return ((System.DateTime)(this[this.tableThread.DateTimeColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Der Wert kann nicht ermittelt werden, da er DBNull ist.", e);
                    }
                }
                set {
                    this[this.tableThread.DateTimeColumn] = value;
                }
            }
            
            public ThreadRow ThreadRowParent {
                get {
                    return ((ThreadRow)(this.GetParentRow(this.Table.ParentRelations["ThreadThread"])));
                }
                set {
                    this.SetParentRow(value, this.Table.ParentRelations["ThreadThread"]);
                }
            }
            
            public bool IsTitleNull() {
                return this.IsNull(this.tableThread.TitleColumn);
            }
            
            public void SetTitleNull() {
                this[this.tableThread.TitleColumn] = System.Convert.DBNull;
            }
            
            public bool IsTextNull() {
                return this.IsNull(this.tableThread.TextColumn);
            }
            
            public void SetTextNull() {
                this[this.tableThread.TextColumn] = System.Convert.DBNull;
            }
            
            public bool IsAuthorNull() {
                return this.IsNull(this.tableThread.AuthorColumn);
            }
            
            public void SetAuthorNull() {
                this[this.tableThread.AuthorColumn] = System.Convert.DBNull;
            }
            
            public bool IsEmailNull() {
                return this.IsNull(this.tableThread.EmailColumn);
            }
            
            public void SetEmailNull() {
                this[this.tableThread.EmailColumn] = System.Convert.DBNull;
            }
            
            public bool IsUserIdNull() {
                return this.IsNull(this.tableThread.UserIdColumn);
            }
            
            public void SetUserIdNull() {
                this[this.tableThread.UserIdColumn] = System.Convert.DBNull;
            }
            
            public bool IsParentNull() {
                return this.IsNull(this.tableThread.ParentColumn);
            }
            
            public void SetParentNull() {
                this[this.tableThread.ParentColumn] = System.Convert.DBNull;
            }
            
            public bool IsDateTimeNull() {
                return this.IsNull(this.tableThread.DateTimeColumn);
            }
            
            public void SetDateTimeNull() {
                this[this.tableThread.DateTimeColumn] = System.Convert.DBNull;
            }
            
            public ThreadRow[] GetThreadRows() {
                return ((ThreadRow[])(this.GetChildRows(this.Table.ChildRelations["ThreadThread"])));
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class ThreadRowChangeEvent : EventArgs {
            
            private ThreadRow eventRow;
            
            private DataRowAction eventAction;
            
            public ThreadRowChangeEvent(ThreadRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public ThreadRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
